# Generated by Django 4.2.23 on 2025-07-20 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("short_name", models.CharField(blank=True, max_length=6, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("lastname", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("ethnicity", models.CharField(blank=True, max_length=50, null=True)),
                ("race", models.CharField(blank=True, max_length=50, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pronouns", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("province", models.CharField(blank=True, max_length=50, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "government_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("primary_email", models.EmailField(max_length=254)),
                (
                    "alternate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("alias1", models.CharField(blank=True, max_length=50, null=True)),
                ("alias2", models.CharField(blank=True, max_length=50, null=True)),
                ("hire_date", models.DateField()),
                ("employment_end_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Leave of Absence", "Leave of Absence"),
                            ("Terminated", "Terminated"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Contractor", "Contractor"),
                            ("Intern", "Intern"),
                            ("Seasonal", "Seasonal"),
                            ("Temporary", "Temporary"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("last_promotion_date", models.DateField(blank=True, null=True)),
                (
                    "work_location_building",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "work_location_office",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("new_hire", models.BooleanField(default=False)),
                ("rehire", models.BooleanField(default=False)),
                ("previous_employee_id", models.IntegerField(blank=True, null=True)),
                (
                    "manager_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="folks.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="folks.employee"
                    ),
                ),
            ],
            options={
                "db_table": "user_roles",
            },
        ),
        migrations.CreateModel(
            name="SalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("Salaried", "Salaried"),
                            ("Hourly", "Hourly"),
                            ("Contract", "Contract"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_bonus_eligible", models.BooleanField(default=False)),
                (
                    "pay_frequency",
                    models.CharField(
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Bi-Weekly", "Bi-Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        default="Bi-Weekly",
                        max_length=20,
                    ),
                ),
                (
                    "annual_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bonus_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("hourly_full_time", models.BooleanField(default=False)),
                ("hourly_start_day", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="folks.employee"
                    ),
                ),
            ],
            options={
                "db_table": "salarydetails",
            },
        ),
        migrations.CreateModel(
            name="RoleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=50)),
                (
                    "job_title_short",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "previous_job_title",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("pay_type", models.CharField(max_length=20)),
                (
                    "reason_for_end",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="folks.department",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="folks.employee"
                    ),
                ),
            ],
            options={
                "db_table": "role_details",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="folks.employee",
            ),
        ),
    ]
