# Generated by Django 4.2.23 on 2025-07-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledetail',
            name='pay_type',
        ),
    ]
