# Generated by Django 4.2.23 on 2025-08-03 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0004_remove_employeehourlyshift_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehourlybreak',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='employeehourlybreak',
            name='break_start_time',
        ),
        migrations.AddField(
            model_name='employeehourlybreak',
            name='break_end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeehourlybreak',
            name='break_start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='alias1',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alias2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
