# Generated by Django 4.2.23 on 2026-03-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0007_leavedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
